name: CI
on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'Dockerfile'
    - '.github/workflows/build.yaml'
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build Image
      env:
        PHP_VERSION: ${{ matrix.php }}-fpm-alpine3.10
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |-
        docker run \
          -v `pwd`:/workspace \
          -v /home/runner/.docker/config.json:/kaniko/.docker/config.json:ro \
          gcr.io/kaniko-project/executor:latest \
          --dockerfile Dockerfile \
          --context dir:///workspace/ \
          --destination ${ECR_REGISTRY}/php:${{ matrix.php }}-${GITHUB_SHA} \
          --build-arg PHP_VERSION=${PHP_VERSION} \
          --cache=true
  check:
    name: Status Check
    runs-on: ubuntu-18.04
    needs: build
    if: failure()
    steps:
    - name: Set Status as Failed
      run: exit 1
