name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build the docker image
      env:
        DOCKER_BUILDKIT: 1
        PHP_VERSION: 7.2-fpm-alpine
      run: docker build . --file Dockerfile --tag tsmd44/php:${GITHUB_SHA} --build-arg PHP_VERSION=${PHP_VERSION}
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u tsmd44
    - name: Push to docker registry
      run: docker push tsmd44/php:${GITHUB_SHA}
