name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u tsmd44 --password-stdin
    - name: Build and push image
      env:
        PHP_VERSION: 7.2-fpm-alpine
      run: |-
        docker run \
        -v `pwd`:/workspace \
        -v /home/runner/.docker/config.json:/kaniko/.docker/config.json:ro \
        gcr.io/kaniko-project/executor:latest \
        --dockerfile Dockerfile \
        --context dir:///workspace/ \
        --destination tsmd44/php:${GITHUB_SHA} \
        --build-arg PHP_VERSION=${PHP_VERSION} \
        --cache=true \
        --cache-repo tsmd44/php-cache \
