name: Check
on:
  check_suite:
    types: [completed]
jobs:
  check:
    name: Check Suite Event
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Echo
      run: echo "Check suite completed"
